# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mayank Singh Rawat
email: mayanks.rawat18@gmail.com
linkedln: https://www.linkedin.com/in/mayank-s-rawat
description: Data Analyst skilled in Python, SQL, and BI tools with experience in automating reporting, building dashboards, and uncovering insights to drive business decisions
github_username: mayank1800
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mayank Singh Rawat"
  avatar : "/assets/images/bio-photo.jpg"   # upload your photo into assets/images
  bio    : "Data Analyst | Python, SQL, BI Tools | Driving insights through data"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mayank-s-rawat"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mayank1800"
    - label: "Resume"
      icon: "fas fa-fw fa-file"
      url: "/assets/files/Mayank_Rawat_Resume.pdf"   # upload your resume here
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mayanks.rawat18@gmail.com"


footer:
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mayank-s-rawat"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mayank1800"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mayanks.rawat18@gmail.com"


defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
